#!/usr/bin/env python3
"""Length gate for added comment blocks: over CAP_LINES/CAP_CHARS without an
exemption marker fails. A mechanical proxy for the length rule in
lint/references/code-comments.md — it never proves a comment useful, and
semantic deletion stays a judgement call there."""

import argparse
import subprocess
import sys
from pathlib import Path
from typing import List, Optional, Sequence, Set, Tuple

CAP_LINES = 3
CAP_CHARS = 240

HASH_EXTS = {"py", "sh", "bash", "zsh", "rb", "pl", "pm", "yaml", "yml", "toml",
             "r", "mk", "ini", "cfg", "conf", "properties", "tf", "tfvars",
             "gemspec", "podspec", "gitignore", "editorconfig"}
HASH_NAMES = {"makefile", "dockerfile", "rakefile"}
SLASH_EXTS = {"c", "cc", "cpp", "cxx", "h", "hh", "hpp", "cs", "java", "js",
              "mjs", "cjs", "ts", "tsx", "jsx", "go", "rs", "swift", "kt",
              "kts", "scala", "php", "dart", "css", "scss", "less", "groovy",
              "jsonc", "proto", "gradle"}
DASH_EXTS = {"sql", "lua", "hs"}
HTML_EXTS = {"html", "htm", "xml", "svg", "vue", "md"}

BANNER_MARKERS = ("spdx", "copyright", "@generated", "auto-generated",
                  "do not edit", "generated by")
REMOVAL_HINTS = ("remove", "removal", "revisit", "upstream")


def _styles(path: str) -> Optional[Set[str]]:
    name = path.rsplit("/", 1)[-1].lower()
    ext = name.rsplit(".", 1)[-1] if "." in name else ""
    styles = set()
    if ext in HASH_EXTS or name in HASH_NAMES:
        styles.add("#")
    if ext in SLASH_EXTS:
        styles.update(("//", "/*"))
    if ext in DASH_EXTS:
        styles.add("--")
    if ext in HTML_EXTS:
        styles.add("<!--")
    return styles or None


def _git(root: str, args: Sequence[str]) -> str:
    process = subprocess.run(
        ["git", "-C", root, *args], capture_output=True, text=True,
        encoding="utf-8", errors="replace", check=False)
    if process.returncode != 0:
        raise SystemExit(
            "comment-gate: git %s failed: %s" % (args[0], (process.stderr or "").strip()))
    return process.stdout


def _hunk_body_size(line: str) -> int:
    """Lines a `@@ -a,b +c,d @@` hunk still owes; `-U0` leaves only +/- lines."""
    total = 0
    for token in line.split()[1:3]:
        if token.startswith(("-", "+")):
            count = token.split(",")[1] if "," in token else "1"
            total += int(count) if count.isdigit() else 1
    return total


def _added(root: str, base: str, paths: Sequence[str]):
    entries: List[Tuple[str, List[Tuple[int, str]]]] = []
    out = _git(root, ["-c", "core.quotePath=false", "diff", "--unified=0",
                      base, "--", *paths])
    path: Optional[str] = None
    lines: List[Tuple[int, str]] = []
    lineno = 0
    pending = 0

    def flush():
        if path is not None and lines:
            entries.append((path, list(lines)))

    for line in out.splitlines():
        if pending > 0:
            # Inside a hunk every line is body, so content like "+++ b/x" is
            # not a header; the `\ No newline` marker owes no hunk line.
            if not line.startswith("\\"):
                pending -= 1
            if line.startswith("+"):
                lines.append((lineno, line[1:]))
                lineno += 1
        elif line.startswith("@@"):
            parts = line.split("+")
            start = parts[1].split(",")[0] if len(parts) > 1 else "1"
            lineno = int(start) if start.isdigit() else 1
            pending = _hunk_body_size(line)
        elif line.startswith("+++ b/"):
            flush()
            path, lines = line[6:], []
        elif line.startswith("+++"):
            flush()
            path, lines = None, []
    flush()
    for name in _git(root, ["ls-files", "--others", "--exclude-standard",
                            "--", *paths]).splitlines():
        if not name.strip():
            continue
        try:
            text = (Path(root) / name).read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        entries.append((name, [(i + 1, item) for i, item in enumerate(text.splitlines())]))
    return entries


def _blocks(path: str, lines: Sequence[Tuple[int, str]]):
    styles = _styles(path)
    if not styles:
        return
    block: List[Tuple[int, str]] = []
    expected: Optional[int] = None
    in_block = False
    for lineno, text in lines:
        stripped = text.lstrip()
        is_comment = in_block
        if in_block:
            if "*/" in stripped or "-->" in stripped:
                in_block = False
        elif "#" in styles and stripped.startswith("#"):
            is_comment = True
        elif "//" in styles and stripped.startswith("//"):
            is_comment = True
        elif "--" in styles and stripped.startswith("--"):
            is_comment = True
        elif "/*" in styles and "/*" in stripped:
            is_comment = True
            if "*/" not in stripped[stripped.index("/*") + 2:]:
                in_block = True
        elif "<!--" in styles and "<!--" in stripped:
            is_comment = True
            if "-->" not in stripped[stripped.index("<!--") + 4:]:
                in_block = True
        if is_comment and expected == lineno:
            block.append((lineno, text))
        elif is_comment:
            if block:
                yield block
            block = [(lineno, text)]
        else:
            if block:
                yield block
            block = []
        expected = lineno + 1
    if block:
        yield block


def main(argv: Optional[Sequence[str]] = None) -> int:
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("repo_root")
    parser.add_argument("--base", default="HEAD")
    parser.add_argument("--paths", nargs="+",
                        help="limit the scan to these pathspecs")
    args = parser.parse_args(argv)
    violations = []
    for path, lines in _added(args.repo_root, args.base, args.paths or ()):
        for block in _blocks(path, lines):
            joined = "\n".join(text for _, text in block).lower()
            if len(block) <= CAP_LINES and sum(len(t) for _, t in block) <= CAP_CHARS:
                continue
            if any(marker in joined for marker in BANNER_MARKERS):
                continue
            if "workaround" in joined and any(hint in joined for hint in REMOVAL_HINTS):
                continue
            violations.append(
                "%s:%d: comment block %d lines/%d chars exceeds %d/%d"
                % (path, block[0][0], len(block),
                   sum(len(t) for _, t in block), CAP_LINES, CAP_CHARS))
    for line in violations:
        print("comment-gate: %s" % line, file=sys.stderr)
    return 1 if violations else 0


if __name__ == "__main__":
    raise SystemExit(main())
